### ISSUE TITLE
Does this build latest chromium?

### ISSUE THREAD

**Issue by EloB** [crosswalk-project/crosswalk-tizen#195]
I'm a bit curious about this project. I been thinking about doing something like this. I'm a smart tv developer and develop tv apps for Samsung and other brands.

I've discovered using webgl then you get a huge performance gain. So I'm writting my app using Pixi.js but Samsung webapp package is using some really legacy chromium. Webgl is still experimental in that package etc.

I was thinking about later versions of chromium could improve my performance even more...

This isn't a "issue" more a question but I don't think stackoverflow would be able to answer this because these niche of development is so small.

Best regards and sorry for my bad english.

**Comment by WonyoungChoi** [comment]
Hello, this crosswalk-tizen project is not managed anymore. You'd better post to the tizen forum instead.
https://developer.tizen.org/forums/web-application-development/active
